### ISSUE TITLE
Cython 3, numpy 2 support 

### ISSUE THREAD

**Issue by fbordeu** [eigency-org/eigency#69]
hello,

I'm trying to port the sources of eigency to support Numpy 2 and cython 3.
For the moment the package compiles but some (most of the) tests fails.

@BTOdell do you already started working on it?

Also, the source have some code for deprecated versions of python. I think we can clean the base code to make the maintenance easier.

I can prepare a PR avec the changes if you are ok.

Felipe

**Comment by BTOdell** [comment]
I haven't started working on support for Numpy 2.

To be honest, I don't have a vested interest in maintaining this project anymore since I no longer work for the company that was using this library in their software.

Maybe we can talk with the repo owner to give you maintainer access and I can step down.

**Comment by BTOdell** [comment]
@wouterboomsma are you active on GitHub still?

**Comment by BTOdell** [comment]
@fbordeu In the mean time, feel free to create a PR with the changes to support Numpy 2 and I can help get it published.

**Comment by fbordeu** [comment]
@BTOdell and @wouterboomsma 

Just make a pull request https://github.com/wouterboomsma/eigency/pull/70
not everything work but is a start. 

I can  ensure the maintenance of the project if you are ok.
I'm happy with the performance and the API of eigency. 
I already manage the conda-forge recipe.

Felipe

**Comment by wouterboomsma** [comment]
Sorry for the slow response. 

Thanks @fbordeu <https://github.com/fbordeu> for taking the initiative to port to Numpy 2 and Cython 3.

@BTOdell <https://github.com/BTOdell>, I understand completely if you would like to step down now that you are no longer actively using it. Thanks for your efforts over the past years! 

Although I originally started this project, I no longer have any time to maintain it - or even to look through PRs. Felipe, should I give you maintainer access? It would basically just mean that you can approve your own PRs - there are no expectations from my side beyond this, but it would just prevent the project from dying. I would also be very happy to move the repo so that it is no longer under my personal github account, if that works better for you.

Cheers,
Wouter

**Comment by fbordeu** [comment]
Hello @wouterboomsma, 

Thanks for the offer of transferring the ownership of the project.  Thank for the work.

I detached my fork of eigency and you can delete your repos and forked again from the new location (under my accout). 
This will make  the repo under my account the "official" (because yours will be only a fork).  I think this is the best way to not break anything (url, scipt) and  people going to your repo will see the link (fork). 

Another point is the licence: I dont know how to deal with it. Any idea??
also the pypi distribution must be transfer ( https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196 )  my pypi login is felipebordeu

Tell me if this is ok with you/

Thanks to @BTOdell  for the work done the last years.
I will try to do my best to keep this project alive.

Felipe

**Comment by wouterboomsma** [comment]
Thanks.

Wouldn’t it be more straightforward to simply transfer the repo - as in https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository? Don’t we lose all issues, watches, stars etc by your approach?

Alternatively, we could create an organization for it, and transfer it there - which would perhaps make it easier for others to step in as maintainers in the future? I don’t have strong preferences.

What is the problem with the licence? Does MIT not work for you?

**Comment by fbordeu** [comment]
That looks perfect. For the moment I prefer a transfer to my account, if more people are interested in contributing and maintaining the project, I will create an organisation.

**Comment by fbordeu** [comment]
For the licence. I just didn't read the licence in detail. I don't know how the notion of property is impacted with the transfers. And also because I will distribute a code with your name on it. Sorry for this part but I want to be sure that we are doing the transfers correctly.

**Comment by fbordeu** [comment]
@wouterboomsma (been a while), so how do you want to proceed so I can keep this project alive?

**Comment by wouterboomsma** [comment]
Hi Felipe

I’m very sorry for the radio silence - I’ve been buried in teaching the last weeks.

The advantage of switching to an organization is that then we would only have to change the URLs in the documentation this one time, and I could remain as co-administrator (if you at some point in the future do not have time to maintain it anymore, would still have administrative permission to the code, and could add other people). But if you have clear preferences for transferring to your personal account, I can probably live with that as well :)

Let me know what you think - and then I’ll initiate the transfer ASAP.

As far as I can see, the next step is then to update pypi to point to the new repo.

You are absolutely right: the licence file should be updated to include all maintainers - including you and Bradley. Such that your names also appear e.g. in the documentation on pypi.

Best,
Wouter

**Comment by Maki4748** [comment]
Please check Pull Request #71 for a fix.

**Comment by fbordeu** [comment]
@wouterboomsma just created the organization to keep this project alive. feel free to transfert the repo.
https://github.com/[eigency-org](https://github.com/eigency-org)

**Comment by fbordeu** [comment]
hi @BTOdell , with the agreement of @wouterboomsma me moved eigency to this new location : https://github.com/eigency-org. Do you want (and have time) to be part of the eigency-org so you  cans easily contribute. No worries if you cant. 

@wouterboomsma do you want to continue doing the packages?? if not you can add me to pypi repository  
( https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196 ) my pypi login is felipebordeu

**Comment by fbordeu** [comment]
I'm going to close this issue, feel free to open new ones to treat specific subjects.
